name: "🔍 Check GitHub Code Index"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # kiểm tra mỗi 3 tiếng

jobs:
  check-index:
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 Checkout repo
        uses: actions/checkout@v4

      - name: 🔎 Query GitHub Search API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${GH_TOKEN}" ]; then
            echo "::error::GH_TOKEN secret is required to query the API"
            exit 1
          fi

          echo "🔍 Checking code indexing status for repo: $GITHUB_REPOSITORY"
          RESPONSE_FILE=$(mktemp)
          STATUS=$(curl -sS \
            -w "%{http_code}" \
            -o "$RESPONSE_FILE" \
            -H "Accept: application/vnd.github.text-match+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            "https://api.github.com/search/code?q=repo:$GITHUB_REPOSITORY&per_page=1")

          if [ "${STATUS}" -ge 400 ]; then
            echo "::error::GitHub API request failed with status ${STATUS}"
            cat "$RESPONSE_FILE"
            exit 1
          fi

          COUNT=$(jq '(.total_count // 0) | tonumber? // 0' "$RESPONSE_FILE")
          rm -f "$RESPONSE_FILE"

          if [ "$COUNT" -gt 0 ]; then
            echo "✅ Repo is indexed. Found $COUNT code entries."
          else
            echo "::warning::Repo not yet indexed. Consider pushing a small change manually to nudge indexing."
          fi
