name: "\U0001F50D Check GitHub Code Index"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *' # kiểm tra mỗi 3 tiếng

jobs:
  check-index:
    runs-on: ubuntu-latest
    steps:
      - name: "\U0001F527 Checkout repo"
        uses: actions/checkout@v4

      - name: "\U0001F50D Query GitHub Search API"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "\U0001F50D Checking code indexing status for repo: $GITHUB_REPOSITORY"
          RESPONSE=$(gh api \
            -H "Accept: application/vnd.github.text-match+json" \
            "search/code?q=repo:$GITHUB_REPOSITORY" || true)

          echo "$RESPONSE" | jq '.total_count' > result.txt
          COUNT=$(cat result.txt)

          if [ "$COUNT" -gt 0 ]; then
            echo "✅ Repo is indexed. Found $COUNT code entries."
          else
            echo "⚠️ Repo not yet indexed. Forcing a reindex trigger..."
            echo " " >> README.md
            git config user.name "index-bot"
            git config user.email "bot@example.com"
            git add README.md
            git commit -m "chore: trigger reindex"
            git push
          fi
